name: 'tavily_elt'
version: '1.0.0'
config-version: 2

profile: 'tavily_elt'  # Match the profile name in your profiles.yml

model-paths: ['models']
test-paths: ['tests']
macro-paths: ['macros']
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_folder:
    staging:
      +materialized: view
    marts:
      +materialized: table